# Generated by Django 4.0.5 on 2022-07-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_bid',
            field=models.PositiveIntegerField(default=100000, verbose_name='시작 입찰가'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.FileField(upload_to='media/', verbose_name='이미지'),
        ),
    ]
