# Generated by Django 4.0.5 on 2022-07-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='painting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.painting'),
        ),
    ]
