# Generated by Django 4.0.5 on 2022-06-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='현재 입찰가'),
        ),
    ]
