# Generated by Django 4.0.5 on 2022-06-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='is_auction',
            field=models.BooleanField(default=True, verbose_name='경매상태'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.FileField(upload_to='paintings/', verbose_name='이미지'),
        ),
    ]
